name: CI (master)

on:
    push:
        branches:
            - master

permissions:
    contents: read

jobs:
    code_checks:
        name: Code checks
        uses: ./.github/workflows/_check_code.yaml

    tests:
        name: Tests
        uses: ./.github/workflows/_tests.yaml
